### ISSUE TITLE
Enhanced Tokenizer - Allow for one or more captures

### ISSUE THREAD

**Issue by unixcow** [adamharrison/lite-xl-simplified#1]
It would be really nice to have the ability to pattern match and apply same token types to any number of matched elements, something like `([%a_][%w_]*)+` in pcre syntax, this would allow for highlighting C++ template parameters like so

```lua
{ 
  pattern = "[<]()([%a_][%w_]*()[,]*)+()[>]",
  type = { "normal", { "literal",  "normal"}, "normal" }
}
```

I know that Lua's pattern matching doesn't allow for that and so the exact syntax for achieving this while maintaining compatibility with Lua pattern matching might be a bit different _(for instance we might use something like the %f to specify that next pattern is matched one or more times)_ but I thought it should be possible now that the tokenizer is using pcre

**Comment by adamharrison** [comment]
So, the normal tokenizer actually uses PCREs, you may want to just post this in the primary repo (https://github.com/lite-xl/lite-xl). Whatever I'm doing in here will mirror whatever eventually ends up happening there.
